name : workflow for creating an artifact
on: [push]

# declare vaiable and use as artifact name
env: 
  ARTIFACT_FILE_NAME: 'README.md'

jobs:
  main:
    runs-on: Ubuntu-Latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }} 
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARTIFACT_FILE_NAME}}
        path: ${{env.ARTIFACT_FILE_NAME}}
